// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/books/:id": {
    params: {
      "id": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/new": {
    params: {};
  };
  "/admin/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/books/:id" | "/admin" | "/admin/new" | "/admin/:id";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/books.$id.tsx": {
    id: "routes/books.$id";
    page: "/books/:id";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/admin.new.tsx": {
    id: "routes/admin.new";
    page: "/admin/new";
  };
  "routes/admin.$id.tsx": {
    id: "routes/admin.$id";
    page: "/admin/:id";
  };
};